language: android
env:
  global:
  - MALLOC_ARENA_MAX=2
  - secure: OKBv4/y2KX+d5LCBgMcPPkXbCJMCcRLsq3eG15y7qls3xfua1gURhaq0G9EgGJweM8obHm1B3xbKpFNg+HIzwiUW6a5H4a+GoS9m9QR3cKgG5GVfmBxYqjCWbPOqakyAsQQVol0ND0zTVin/BhfhVNPvC3MP7Aor2M0F+gRNb1YuB5kS6FtOAaM4hAsZ1WHNXV01FpqrPbM7QEoTI2CUMcFC7ow5bz1CzvRNysbEGcZUGbcfWXkCNmUz+3PYiHKzuiu2arDYXUMkjNwtILLEAgGWiTY6ZwCjPIot08aWkXvBvdiwas3BjVB0JeUmeZEGdZd7TYaldRMGQPsYKB4MnkGT8gpwQFpRY6Y08fuwJga2vcxXXSnjLJw08cp1Dd53JT5OPltE5iZwpjia6TEj33ZLs9OBPNAQtyGyPL0ARnhDEOTFCuECntEHKlX/a1Zv6HhDBe99qeZipR7Gh37vDSkEOthYaIrOEPuh8vTUHP/066D2U1r9kcgUovzT9aUBvDlOiDDuulcEgqMib4tNCaoPWC/Eq9rNOsFJIV3SU0DCtNN3ffMHuJp+0G+rycKs2ruBTskzTFmhEa11a6mM7x87nwo8JfFV0AnsW+5tDfejEVJ8XboW7Aj5giA802CHt2/c/firg2RZRh4HCw9/pheKNQzWID2JZZdTBb55KKs=
  - secure: yh6DtTT2s5rt9Y3i5DmpNuFxYQrSzJXTGYnTClswqS1SAjX6Tz+0T+Yfc8TpCoyFax+7TDRLSHo/EgeJmUc+IAVHGXTgxuJIANObe/S4npqfWnq30mn7PBq0R1cT5no+4ndTl11NQdhwldvafqRHVXliLDaKjnT+SrX7lQEvF7pmmYz9acEJu3mZCphvHSn1foFglTPTa6G/vsSChI0fNaUi0p7hRDPKl0Fx7jZWMdBlF6Yn0iiKh3k4AaQYrKdpKQKQHsgzPEHoACWemembZW6LfJcGOC/EgcSGfmx826o93iVDr6AJNOWFlofWcLc3X0DZVRkRqgDWhCuenwRw7eJmTyzRyRKF7XGzACNqdWJ3NCbm9sYiocqJBzMf1wmYdICVqqYYZx674QjrSL0/S6A4Lh7DutHNOyM4g75a8UwM/3ConQEfIUrlDQKgvqzf8czX97wc4SSds9WhDjjU4OTo096CsuOsygM3T+0DJS/eIIh1om5q2/cknKl9CKxq4vmiWNBqh4Hyvm9Pn5olfPBx1kfNIVpqPcOeO0IdQ/5h0kfauGKyI4LiR0ou4w9ZdEDbvrSIciLzhkWXMRjS6sI3yiKBMH+7DO2O+xTNIYvmGU8ea73rtBaRzROsZLpK6epjS/tHy6F+6mjVxMV+bxgKL1/KgvvawS2Fs+gHeEs=
  matrix:
  - ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    ENABLE_GPL_THIRD_PARTIES=0 BUILD_VIDEO=1 BUILD_OPENH264=1 ENABLE_OPENH264_DECODER=1
    BUILD_X264=0 BUILD_AMRNB=full BUILD_AMRWB=1 BUILD_ZRTP=1 BUILD_SILK=1 BUILD_G729=1
    BUILD_TUNNEL=0 BUILD_WEBRTC_AECM=1 USE_JAVAH=1 BUILD_FOR_X86=1 BUILD_SQLITE=1
    BUILD_TLS=1 BUILD_WEBRTC_ISAC=1 BUILD_OPUS=1 BUILD_UPNP=1 BUILD_MATROSKA=0 BUILD_ILBC=1
sudo: false
addons:
  apt:
    packages:
    - yasm
    - nasm
    - curl
    - ant
    - rsync
    - autoconf
    - automake
    - libtool
    - pkg-config
    - bc
    - libwww-perl
    - ruby
cache:
  apt: true
  bundler: true
  ccache: true
  directories:
  - "$HOME/.ccache"
before_install:
- if [ `uname -m` = x86_64 ]; then wget --timeout=120 http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin
  -O ndk.bin ; else wget --timeout=120 http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86.bin
  -O ndk.bin ; fi
- chmod 755 ndk.bin ; ./ndk.bin 2>&1 | grep -v Extracting
- export ANDROID_NDK=$PWD/android-ndk-r10e
- export PATH=${ANDROID_NDK}:${ANDROID_NDK}/ndk-build:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:$PATH
- export NDK_CACHE=ccache
- export ANDROID_MOST_RECENT_TARGET=android-19
- which bundler || gem install bundler
- bundle install
android:
  components:
  - build-tools-19.1.0
  - build-tools-20.0.0
  - build-tools-22.0.1
  - android-19
  - android-20
  - android-22
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - addon-google_apis-google-20
  - addon-google_apis-google-22
before_script:
- echo "Starting to update submodules"
- if [ ! -d submodules/linphone/oRTP/.git ]; then rm -fr submodules/linphone/oRTP/
  ; git clone git://git.linphone.org/ortp.git submodules/linphone/oRTP ; fi
- if [ ! -d submodules/linphone/mediastreamer2/.git ]; then rm -fr submodules/linphone/mediastreamer2/
  ; git clone git://git.linphone.org/mediastreamer2.git submodules/linphone/mediastreamer2
  ; fi
- if [ ! -d submodules/mswebrtc/webrtc/.git ]; then rm -fr submodules/mswebrtc/webrtc/
  ; git clone git://git.linphone.org/webrtc.git submodules/mswebrtc/webrtc ; fi
- git submodule update --init --recursive
- echo "Finished updating submodules"
- android list target -c
script:
- "./Tools/git_version.sh"
- "./Tools/travis_script.sh"
after_success:
- "./Tools/release.sh"
notifications:
  flowdock:
    secure: eD1JpGzIf8paOU14pFK1G3VUXDLBiybGHf0WHX8spmvfSo3O5n3xFEq0qrcc6bAuXxrhSVRqt9k2fKQshRf/rfgkRjmcwXtvyLYH6gND3RxnMbicAUJCNXFMSEEPKPEGtWXUM2soDgNm7q0vc32wpRJLq+iDjZAHuBYgaJXIW6wI4Ny3HSiHzIBNF7sKpH6uVDCSwVYotfuT8zqQRUHw9C1Ed+Cs10/w7eH0F2l79RsNhepxaV2F3bQQzsMfHffAtMg+j1lzGayQlOObi0qrI0TkRHLqgp6H0F/cFq+QBFXtQqyhdO3VTYNW2Iju8dJCx55Ns9a3fzXyejvXAPmqmKEH+BHj0Yde9KaRVVHW0+os1ZPBOLyUm9jOUcpFaz13jMmQNigazszq9+AYyrvIQYewDr306W5t8ELbz6GDVRNcxVwU8djwL1Qi1OQb5emawgV3NOnsWD4x+aBI7V+QJZr5epweUwfkxnf+4IiCO0mAvlcB3bfNbO0G/M4R+l0UMc2llrbYpy94NCj3qackkghxI7E6KL6ByzOCcHBDBGW2uhGwu4mlLjv5WFutS7R5wX1yzNSD0sbJDV7UOonGgPQIXrgUeGCijEaNm/NB70VX4YRJbaxDDzkZTB29E/psigIqJf72hJB6zho/p72wPAWFzLeWlnoHLQCJqG0M+2w=
